apiVersion: v1
kind: Service
metadata:
  name: orion-app-service
  labels:
    app: orion-app-app
spec:
  ports:
  - name: metrics-svc-port
    port: 80
    targetPort: 8080
  selector:
    app: orion-app
