prometheus:
  url: http://mon-kube-prometheus-stack-prometheus.monitoring.svc

rules:
  default: false
  custom:
  - seriesQuery: '{namespace="default",service="orion-app-service"}'
    resources:
      overrides:
        namespace:
          resource: "namespace"
        service:
          resource: "service"
    # name:
    #   matches: "(.*)"
    metricsQuery: 'avg(sum_over_time(total_hit_count{pod=~"orion-app-deploy-(.*)"}[2m])) by (service)'
